version: "2"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: ciservice-master
    ports:
     - 8080:8080
     - 8085:50000

  sonarqube:
    image: sonarqube
    container_name: ciservice-sonarqube
    ports:
      - "8020:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    container_name: ciservice-postgresql
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  
  gitlab:
    image: jtoledog/ciservice:gitlab
    container_name: ciservice-gitlab
    hostname: 192.168.50.10
    ports:
      - "8030:80"
      - "8031:443"
      - "8032:22"
    volumes:
      - gitlab_conf:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

  nexus:
    image: sonatype/nexus
    container_name: ciservice-nexus
    ports:
      - "8081:8081"

  slave:
    image: centos7
    container_name: ciservice-slave
    ports:
      - "8040:22"

volumes:
  # GitLab CE Volumes
  gitlab_conf:
    driver_opts:
      type: none
      device: /vagrant/volumes/gitlab/config
      o: bind
  gitlab_logs:
    driver_opts:
      type: none
      device: /vagrant/volumes/gitlab/logs
      o: bind
  gitlab_data:
    driver_opts:
      type: none
      device: /vagrant/volumes/gitlab/data
      o: bind

  # PostgreSQL Volumes
  postgresql:
    driver_opts:
      type: none
      device: /vagrant/volumes/postgresql/config
      o: bind
  postgresql_data:
    driver_opts:
      type: none
      device: /vagrant/volumes/postgresql/data
      o: bind

  # SonarQube Volumes
  sonarqube_conf:
    driver_opts:
      type: none
      device: /vagrant/volumes/sonarqube/opts
      o: bind
  sonarqube_data:
    driver_opts:
      type: none
      device: /vagrant/volumes/sonarqube/data
      o: bind
  sonarqube_extensions:
    driver_opts:
      type: none
      device: /vagrant/volumes/sonarqube/extensions
      o: bind
  sonarqube_bundled-plugins:
    driver_opts:
      type: none
      device: /vagrant/volumes/sonarqube/plugins
      o: bind