version: "2"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: ciservice-master
    ports:
     - 8080:8080
     - 8085:50000

  sonarqube:
    image: sonarqube
    container_name: ciservice-sonar
    ports:
      - "8020:9000"
      - "8021:9092"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    
  db:
    image: postgres
    container_name: ciservice-db-sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
  
  gitlab:
    image: jtoledog/ciservice:gitlab
    container_name: ciservice-gitlab
    hostname: 192.168.50.10
    ports:
      - "8030:80"
      - "8031:443"
      - "8032:22"
    volumes:
      - gitlab_conf:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

  nexus:
    image: sonatype/nexus
    container_name: ciservice-nexus
    ports:
      - "8081:8081"

  slave:
    image: centos7
    container_name: ciservice-slave
    ports:
      - "8040:22"

volumes:
  gitlab_conf:
    driver_opts:
      type: none
      device: /vagrant/gitlab/config
      o: bind
  gitlab_logs:
    driver_opts:
      type: none
      device: /vagrant/gitlab/logs
      o: bind
  gitlab_data:
    driver_opts:
      type: none
      device: /vagrant/gitlab/data
      o: bind
