FROM jenkins
MAINTAINER jtoledog <jptgjuanpablo@gmail.com>
USER root
RUN apt-get update && apt-get install -y ruby make more-thing-here
USER jenkins # drop back to the regular jenkins user - good practice