FROM jtoledog/ciservice:master
#This is the original jenkins docker in the 2.108 version
MAINTAINER jtoledog <jptgjuanpablo@gmail.com>

#ADD ./jenkins_initial_home.tar.gz /var/jenkins_home/jenkins_initial_home.tar.gz
#RUN cd /var/jenkins_home/; ls -lsh; tar xvf jenkins_initial_home.tar.gz; rm jenkins_initial_home.tar.gz